### ISSUE TITLE
enable PlacementDecision to reflect AddOnPlacementScore more frequently than every 5 minutes 

### ISSUE THREAD

**Issue by juliev0** [open-cluster-management-io/placement#87] opened 2022-11-13 22:48 UTC
Apparently, `PlacementDecision` is only updated once every 5 minutes to reflect the `AddOnPlacementScore`. For CRD's that are scheduled frequently, this could mean placing them on nodes that are no longer available. 

Is it possible to make it configurable such that the `AddOnPlacementScore` change causes an update to the `PlacementDecision` or to make the 5 minutes configurable? Or if something else is advised, feel free to comment.

**Comment by mikeshng** [comment] 2022-11-17 00:46
Hi @qiujian16 @haoqing0110 @elgnay 
The Argo Workflow team seems to be interested in getting a more up to date placement decision. Any ideas how we can make this interval a configurable option? Thanks.

**Comment by rokej** [comment] 2022-11-17 03:46
Service delivery team is going to rely on this to make decision on where to place a new hosted cluster. 5 minutes seem too long for a placement decision to still be valid.

**Comment by haoqing0110** [comment] 2022-11-17 07:12
As @qiujian16 mentioned in the community meeting, a possible way is to take advantage of [ValidUntil](https://github.com/open-cluster-management-io/api/blob/main/cluster/v1alpha1/types_addonplacementscore.go#L45) time of the `AddOnPlacementScore` to trigger reschedule.

The score provider needs to set the `ValidUntil` to a shorter time if the score changes frequently. 

And in placement, the addon score plugin will go through all the filtered clusters, get each cluster's `AddOnPlacementScore` `ValidUntil`, and calculate the placement [RequeueAfter](https://github.com/open-cluster-management-io/placement/blob/main/pkg/plugins/interface.go#L35) time.
```
// 10s is an example value, it would be a hard code time. It the minimum requeue time.
minRequeueTime = 10s 

// 5s is an example value, it would be a hard code time
// It means the placement would be requeued 5s before the score expire.
requeueTime=min(ValidUntil) - 5s 

if requeueTime < minRequeueTime {
   requeueTime = minRequeueTime
}

```

**Comment by haoqing0110** [comment] 2022-11-17 07:16
@mikeshng @rokej above is a possible way to trigger updates more promptly when scores change. Want to know your comments on this.

**Comment by haoqing0110** [comment] 2022-11-17 07:27
@juliev0 @mikeshng @rokej above is a possible way to trigger updates more promptly when scores change. Want to know your comments on this.

**Comment by mikeshng** [comment] 2022-11-17 14:43
Hi @juliev0 @rokej @jnpacker ,
Qing Hao and Qiu Jian are suggesting using the `validUntil` status field to trigger the Placement reconciliation (re-evaluate scores). What do you all think?
Just a note, as confirmed with Qing Hao on Slack, even if users populate the `validUntil` field right now (OCM API v0.9.0), it will not trigger the reconciliation yet. The Placement maintainers or community contributors will need to enhance the `RequeueAfter` logic in the addon Placement plugin in order for everything to work together.

**Comment by juliev0** [comment] 2022-11-18 01:46
@haoqing0110 @mikeshng Thanks for the prompt response. It seems like what you’re saying does take care of the concern.

**Comment by rokej** [comment] 2022-11-22 23:07
@juliev0 @haoqing0110 @mikeshng I find it kind of odd to set `validUntil` in `AddOnPlacementScore` status. This means if the score changes within valid time period, the score change is invalid.

**Comment by haoqing0110** [comment] 2022-11-23 06:55
@rokej Hmm, I think if a score has `validUntil` time1,  and then the score changes within the time1, the score change will reflect on the decision at the `requeueTime`, which is the (`time1` - 5s) or the minRequeueTime. Not sure if this can resolve your concern, or would you like to give a detailed example?

**Comment by qiujian16** [comment] 2022-11-23 09:29
I think it is valid, and any score change should also update validUntil field

**Comment by rokej** [comment] 2022-11-23 22:46
@qiujian16 @haoqing0110 I am not sure if I agree. I think it depends on the type of score but in general I would think that a score life-cycle controller should keep the score up-to-date with no delay whenever the score changes. So in this case, the score is valid until it is updated again. There is no validUntil time for this.

The real ask is .. how can the placement API change its decision as soon as the score changes? I am not sure if using `validUntil` for this purpose is the right approach.

**Comment by qiujian16** [comment] 2022-11-24 00:21
e.g.
1. at time1, score controller update the score and validUntil to time1+10 seconds
2. at time1+5, score controller updates the score and validUntil to time1+5+10 seconds

under this situation, when placement controller honor the score at the first time
1. it will revisit the score at time1+8 seconds (80% of valid until)
2. at time1+8 seconds, if it will revisit the score at time1+5+8 seconds

We can not watch the score because it may have scale problem, and can easily make decision dangling. Use valid until gives each score controller the capability to tell placement controller how frequent the score will be updated, so that placement controller can adjust the requeue time based on that.

@haoqing0110 think twice, I think we should do some test on score watch. I think with some index, we can easily find which placements are impacted upon score change in placement controller.

**Comment by haoqing0110** [comment] 2022-12-23 01:34
This issue is resolved by https://github.com/open-cluster-management-io/placement/pull/89.
/close

**Closed by haoqing0110** 2022-12-23 01:34 UTC
